[tool.poetry]
name = "corpuspy"
version = "0.1.0"
description = "corpuspy - Python corpus infrastructure"
authors = ["Tarepan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tarepan/corpuspy"


[tool.poetry.dependencies]
python = "^3.7.1"
fsspec = {version = ">=2021.5.0", extras = ["s3"]}
requests = "^2.25.1"
tqdm = "^4.54.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
