[tool.poetry]
name = "corpuspy"
version = "0.0.2"
description = "corpuspy - Python corpus infrastructure"
authors = ["Tarepan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tarepan/corpuspy"


[tool.poetry.dependencies]
python = "^3.6.1"
fsspec = {extras = ["s3"], version = "^0.8.4"}
requests = "^2.25.1"
tqdm = "^4.54.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
