[tool.poetry]
name = "speechcorpusy"
version = "2.1.0"
description = "speechcorpusy - Python corpus handler & infrastructure"
authors = ["Tarepan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tarepan/speechcorpusy"


[tool.poetry.dependencies]
python = "^3.7"
fsspec = {version = ">=2021.5.0", extras = ["s3"]}
requests = "^2.25.1"
tqdm = "^4.54.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
